### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by xiaosadexiaohai** [firebroo/nginx-confd#1]
![image](https://user-images.githubusercontent.com/18409309/62119466-39057700-b2f2-11e9-9858-829c7a8ce7e7.png)
logyi'zh
一直提示这个
配置表如下:
![image](https://user-images.githubusercontent.com/18409309/62119507-563a4580-b2f2-11e9-85c2-aa1490ba68f9.png)

**Comment by xiaosadexiaohai** [comment]
使用的是yum install nginx -y 默认的配置表

**Comment by xiaosadexiaohai** [comment]
@firebroo

**Comment by firebroo** [comment]
@xiaosadexiaohai 你添加一个配置再启动应该就可以了。

**Comment by firebroo** [comment]
@xiaosadexiaohai 随便加个
server {
        listen 80 reuseport;
        server_name test.intra.firebroo.com;
        location / {
            proxy_pass http://127.0.0.1:8080;
        }
    }

**Comment by xiaosadexiaohai** [comment]
可以了 3Q
